config/routes.rb
Social::Application.routes.draw do
  root 'welcome#index'
  
  get "users/:user_id/posts/:id/show", to: "posts#show", as: "show_post"
  
  get "comments/show/:id", to: "comments#show", as: "show_comment"
  
  get "comments/down_vote/:id", to: "comments#down_vote", as: "down_vote_comment"
  
  get "comments/up_vote/:id", to: "comments#up_vote", as: "up_vote_comment"
  
  get "posts/down_vote/:id", to: "posts#down_vote", as: "down_vote_post"
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "proposals/up_vote/:id", to: "proposals#up_vote", as: "up_vote_proposal"
  
  get "proposals/down_vote/:id", to: "proposals#down_vote", as: "down_vote_proposal"
  
  get "shares/up_vote/:id", to: "shares#up_vote", as: "up_vote_share"
  
  get "shares/down_vote/:id", to: "shares#down_vote", as: "down_vote_share"
  
  delete "users/:user_id", to: "notifications#clear", as: "clear"
  
  get "groups/groups_joined/:id", to: "groups#groups_joined", as: "groups_joined"
  
  delete "members/leave/:id", to: "members#destroy", as: "leave_group"
  
  post "members/join/:id", to: "members#create", as: "join_group"
  
  get "members/request_to_join/:id", to: "members#request_to_join", as: "request_to_join"
  
  post "posts/share/:id", to: "posts#share", as: "share"
  
  delete "connections/destroy/:id", to: "connections#destroy", as: "unfollow"
  
  post "connections/create/:id", to: "connections#create", as: "follow"
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  post "hashtags/follow/:id", to: "hashtags#follow", as: "follow_tag"
  
  get "posts/new_comment/:id", to: "posts#new_comment", as: "new_comment_ajax"
  
  get "proposals/menu/:proposal_id", to: "proposals#menu", as: "change_proposal_menu"
  
  get "groups/:group_id/proposals/menu", to: "proposals#menu", as: "proposal_menu"
  
  get "federations/:federation_id/proposals/menu", to: "proposals#menu", as: "federation_proposal_menu"
  
  get "groups/:group_id/federations", to: "groups#federations", as: "federations"
  
  delete "users/destroy/:id", to: "users#destroy", as: "user_destroy"
  
  get "users/:user_id/connections", to: "users#connections", as: "user_connections"
  
  get "proposals/new/:proposal_id", to: "proposals#new", as: "new_proposal"
  
  get "proposals/show/:id", to: "proposals#show", as: "proposal"
  
  post "folders/create", as: "create_folder"
  
  post "proposals/create", as: "proposals"
  
  patch "posts/update", as: "update_post"
  
  post "comments/create", as: "comments"
  
  post "messages/create", as: "messages"
  
  get "users/settings", as: "settings"
  
  post "posts/create", as: "posts"
  
  post "shares/create", as: "shares"
  
  get "search/search", as: "search"
  
  get "welcome/about", as: "about"
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  get "sessions/destroy"
  
  get "sessions/new"
  

  
  resources :groups, :federations do
    resources :shares
    resources :members
    resources :code_modules
    resources :proposals do
      resources :comments
    end
  end
  
  resources :users do
    resources :notifications
    member do
      get :following, :followers
    end
    resources :posts do 
      resources :comments
    end
  end
  
  resources :sessions
  resources :connections
  
  resources :folders do
    resources :messages
  end

end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  belongs_to :federation
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  validates_presence_of :name, :description
  
  mount_uploader :image, ImageUploader
  
  def open_to?(user)
    if group_id
      members = Group.find(group_id).members
    elsif federation_id
      members = Federation.find(federation_id).members
    end
    if open or (!open and members.find_by_user_id(user.id).reputation and \
      members.find_by_user_id(user.id).reputation > 0)
      true
    end
  end
  
  def add_to_reputation
    if group_id
      member = Group.find(group_id).members.find_by_user_id(user_id)
    elsif federation_id
      member = Federation.find(federation_id).members.find_by_user_id(user_id)
    end
    if member.reputation
      member.update reputation: member.reputation + 1
    else
      member.update reputation: 1
    end
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def up_vote
    @share = Share.find(params[:id])
    if Vote.up_vote!(@share, current_user)
      User.find(@share.user_id).notify!(:up_vote_share, current_user, @share.id)
      @share.add_to_reputation
      redirect_to :back
    else
      redirect_to :back
    end
  end
  
  def down_vote
    @share = Share.find(params[:id])
    Vote.down_vote!(@share, current_user)
    redirect_to :back
  end
  
  def new
    @share = Share.new
  end
  
  def create
    if params[:group_id]
      @group = Group.find(params[:group_id])
      _obj = @group
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
      _obj = @federation
    end
    @share = _obj.shares.new(params[:share].permit(:name,
      :description, :good, :service, :image, :open))
    @share.user_id = current_user.id
    
    if @share.save
      flash[:notice] = "The share was successfully posted."
      if @group
        redirect_to group_shares_path(@group)
      elsif @federation
        redirect_to federation_shares_path(@federation)
      end
    else
      flash[:error] = "Invalid input."
      redirect_to :back
    end
  end
  
  def show
    if params[:group_id]
      @group = Group.find(params[:group_id])
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
    end
    @share = Share.find(params[:id])
    @comments = @share.comments
    @comment = Comment.new
  end
  
  def index
    if params[:group_id]
      @group = Group.find(params[:group_id])
      @shares = @group.shares.all.reverse
      
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
      @shares = @federation.shares.all.reverse
    end
  end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_card.html.erb
<!-- shares -->

<% if share.open_to? current_user %>
	<div id="card">
		<div align="center">
			<h4><%= share.name %></h4>
			<p><%= share.description %></p>
	
			<div class="btn-group">
				<% if current_user.id != share.user_id %>
					<%= render "shares/vote_buttons", share: share %>
				<% end %>
				<%= render "shares/comment_button", share: share %>
			</div>
		</div>
	</div>
<% end %>

app/views/shares/_comment_button.html.erb
<!-- shares -->

<% if @group %>
	<%= link_to group_share_path(@group, share), class: "btn btn-default" do %>
		<span class="glyphicon glyphicon-comment"></span>
	<% end %>
<% elsif @federation %>
	<%= link_to federation_share_path(@federation, share), class: "btn btn-default" do %>
		<span class="glyphicon glyphicon-comment"></span>
	<% end %>
<% end %>

app/views/shares/_new.html.erb
<!-- shares -->

<% if current_user %>
	<div id="card">
		<%= form_for @share, :html => {:multipart => true, "data-ajax" => false} do |f| %>
			<%= hidden_field_tag :group_id, params[:group_id] %>
			<p>
				<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
			</p>
			<p>
				<%= f.text_area :description, placeholder: "Description", class: "form-control" %>
			</p>
			<p>
				<%= f.file_field :image, class: "form-control" %>
			</p>
			<p>
				<%= f.submit "Share", class: "btn btn-default btn-lg btn-block" %>
			</p>
		<% end %>
	</div>
	<br>
<% end %>

app/views/shares/_vote_buttons.html.erb
<!-- shares -->

<% if @group.membership(current_user) or @federation %>
	<%= link_to(up_vote_share_path(share), class: "btn btn-default") do %>
		<span class="glyphicon glyphicon-chevron-up"></span>
	<% end %>
	<%= link_to(down_vote_share_path(share), class: "btn btn-default") do %>
		<span class="glyphicon glyphicon-chevron-down"></span>
	<% end %>
<% end %>

app/views/shares/index.html.erb
<!-- shares -->

<%= render "groups/name_heading", item: "Shares" if @group %>

<%= render "federations/name_heading", item: "Shares" if @federation %>

<% if current_user %>
	<div id="large_button">
		<% if @group %>
			<%= link_to "Offer something to share", new_group_share_path(@group),
				class: "btn btn-default btn-lg btn-block" %>
		<% elsif @federation %>
			<%= link_to "Offer something to share", new_federation_share_path(@federation),
				class: "btn btn-default btn-lg btn-block" %>
		<% end %>
	</div><br>
<% end %>

<% for share in @shares %>
	<%= render "shares/card", share: share %>
<% end %>

app/views/shares/new.html.erb
<!-- shares -->

<% if current_user %>
	<div id="card">
		<div id="form_padding">
		<%= form_for @share, :html => {:multipart => true, "data-ajax" => false} do |f| %>
			<%= hidden_field_tag :federation_id, params[:federation_id] if params[:federation_id] %>
			<%= hidden_field_tag :group_id, params[:group_id] if params[:group_id] %>
			
			<p>
				<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
			</p>
			<p>
				<%= f.text_area :description, placeholder: "Description", class: "form-control" %>
			</p>
			<p>
				<%= f.file_field :image, class: "form-control" %>
			</p>
			<p>
				<%= f.select :open,
					options_for_select([["Open or Closed", nil], ["Open (anyone can partake)", true],
					["Closed (active contributors only)", false]]), {}, { class: "form-control" } %>
			</p>
			<p>
				<%= f.submit "Share", class: "btn btn-default btn-lg btn-block" %>
			</p>
		<% end %>
		</div>
	</div>
	<br>
<% end %>

app/views/shares/show.html.erb
<!-- shares -->

<%= render "shares/card", share: @share %>

<%= render "comments/new", item: :share %>

<%= render "comments/comments" %>