config/routes.rb
Social::Application.routes.draw do
  root 'welcome#index'
  
  get "users/:user_id/posts/:id/show", to: "posts#show", as: "show_post"
  
  get "comments/show/:id", to: "comments#show", as: "show_comment"
  
  get "comments/down_vote/:id", to: "comments#down_vote", as: "down_vote_comment"
  
  get "comments/up_vote/:id", to: "comments#up_vote", as: "up_vote_comment"
  
  get "posts/down_vote/:id", to: "posts#down_vote", as: "down_vote_post"
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "proposals/up_vote/:id", to: "proposals#up_vote", as: "up_vote_proposal"
  
  get "proposals/down_vote/:id", to: "proposals#down_vote", as: "down_vote_proposal"
  
  get "shares/up_vote/:id", to: "shares#up_vote", as: "up_vote_share"
  
  get "shares/down_vote/:id", to: "shares#down_vote", as: "down_vote_share"
  
  delete "users/:user_id", to: "notifications#clear", as: "clear"
  
  get "groups/groups_joined/:id", to: "groups#groups_joined", as: "groups_joined"
  
  delete "members/leave/:id", to: "members#destroy", as: "leave_group"
  
  post "members/join/:id", to: "members#create", as: "join_group"
  
  get "members/request_to_join/:id", to: "members#request_to_join", as: "request_to_join"
  
  post "posts/share/:id", to: "posts#share", as: "share"
  
  delete "connections/destroy/:id", to: "connections#destroy", as: "unfollow"
  
  post "connections/create/:id", to: "connections#create", as: "follow"
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  post "hashtags/follow/:id", to: "hashtags#follow", as: "follow_tag"
  
  get "posts/new_comment/:id", to: "posts#new_comment", as: "new_comment_ajax"
  
  get "proposals/menu/:proposal_id", to: "proposals#menu", as: "change_proposal_menu"
  
  get "groups/:group_id/proposals/menu", to: "proposals#menu", as: "proposal_menu"
  
  get "federations/:federation_id/proposals/menu", to: "proposals#menu", as: "federation_proposal_menu"
  
  get "groups/:group_id/federations", to: "groups#federations", as: "federations"
  
  delete "users/destroy/:id", to: "users#destroy", as: "user_destroy"
  
  get "users/:user_id/connections", to: "users#connections", as: "user_connections"
  
  get "proposals/new/:proposal_id", to: "proposals#new", as: "new_proposal"
  
  get "proposals/show/:id", to: "proposals#show", as: "proposal"
  
  post "folders/create", as: "create_folder"
  
  post "proposals/create", as: "proposals"
  
  patch "posts/update", as: "update_post"
  
  post "comments/create", as: "comments"
  
  post "messages/create", as: "messages"
  
  get "users/settings", as: "settings"
  
  post "posts/create", as: "posts"
  
  post "shares/create", as: "shares"
  
  get "search/search", as: "search"
  
  get "welcome/about", as: "about"
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  get "sessions/destroy"
  
  get "sessions/new"
  

  
  resources :groups, :federations do
    resources :shares
    resources :members
    resources :code_modules
    resources :proposals do
      resources :comments
    end
  end
  
  resources :users do
    resources :notifications
    member do
      get :following, :followers
    end
    resources :posts do 
      resources :comments
    end
  end
  
  resources :sessions
  resources :connections
  
  resources :folders do
    resources :messages
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true
  
  def self.unchecked
    where(checked: false)
  end
end

app/controllers/notifications_controller.rb
# may need to add integer for post id's or user id's as well as a string for action type
# a clear all button to delete all notifications

class NotificationsController < ApplicationController
  def index
    reset_page
    if current_user
      @notes = paginate current_user.notifications.last(10)
      current_user.notifications.update_all checked: true
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_time_ago.html.erb
<!-- notifications -->

<!-- time variables gets set -->
<% time_ago = time_ago_in_words(note.created_at) + " ago" %>
<% if time_ago.include? "about" %>
	<% time_ago.slice! "about " %>
<% end %>

<%= link_to time_ago, user_notifications_path(current_user), id: :top_right_time %>

app/views/notifications/index.html.erb
<!-- notifications -->

<% if current_user %>
	<% @notes.each do |note| %>
		<div id=<%= color_theme("card")%>>
			<%= render "notifications/time_ago", note: note %>
			<table align="center" id="note_message">
				<tr>
					<td><%= profile_picture(User.find(note.other_user), "25x25") %></td>
					<td>
						<% case note.action.to_sym %>
							<% when :follow %>
								<%= link_to note.message, user_path(note.other_user) %>
							<% when :message %>
								<%= link_to note.message, folder_path(note.item) %>
							<% when :comment, :up_vote %>
								<%= link_to note.message, show_post_path(note.user, note.item) %>
							<% when :reply %>
								<%= link_to note.message, show_comment_path(note.item) %>
							<% when :share_post %>
								<!-- has to link to sharers post, not the original users -->
								<%= link_to note.message, show_post_path(note.other_user, note.item)%>
							<% when :mention %>
								<%= link_to note.message, show_post_path(note.other_user, note.item) %>
								
							<% when :comment_proposal, :up_vote_proposal %>
								<% if Proposal.find(note.item).group_id %>
									<%= link_to note.message, group_proposal_path(Group.find( \
									Proposal.find(note.item).group_id), note.item) %>
								<% elsif Proposal.find(note.item).federation_id %>
									<%= link_to note.message, federation_proposal_path(Federation.find( \
									Proposal.find(note.item).federation_id), note.item) %>
								<% elsif Proposal.find(note.item).proposal_id %>
									<%= link_to note.message, proposal_path(Proposal.find(note.item)) %>
								<% end %>
								
							<% when :comment_share, :up_vote_share %>
								<% if Share.find(note.item).group_id %>
									<%= link_to note.message, group_share_path(Group.find( \
									Share.find(note.item).group_id), note.item) %>
								<% elsif Share.find(note.item).federation_id %>
									<%= link_to note.message, federation_share_path(Federation.find( \
									Share.find(note.item).federation_id), note.item) %>
								<% end %>
						<% end %>
					</td>
				</tr>
			</table>
		</div>
	<% end %>

	<%= render "pages/more_back", all_items: current_user.notifications, items: @notes %>
	
	<% if current_user.notifications.empty? %>
		<div id="card">
			<div align="center">You have zero notifications.</div>
		</div>
	<% end %>
<% end %>