config/routes.rb
Social::Application.routes.draw do
  root 'welcome#index'
  
  get "users/:user_id/posts/:id/show", to: "posts#show", as: "show_post"
  
  get "comments/show/:id", to: "comments#show", as: "show_comment"
  
  get "comments/down_vote/:id", to: "comments#down_vote", as: "down_vote_comment"
  
  get "comments/up_vote/:id", to: "comments#up_vote", as: "up_vote_comment"
  
  get "posts/down_vote/:id", to: "posts#down_vote", as: "down_vote_post"
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "proposals/up_vote/:id", to: "proposals#up_vote", as: "up_vote_proposal"
  
  get "proposals/down_vote/:id", to: "proposals#down_vote", as: "down_vote_proposal"
  
  get "shares/up_vote/:id", to: "shares#up_vote", as: "up_vote_share"
  
  get "shares/down_vote/:id", to: "shares#down_vote", as: "down_vote_share"
  
  delete "users/:user_id", to: "notifications#clear", as: "clear"
  
  get "groups/groups_joined/:id", to: "groups#groups_joined", as: "groups_joined"
  
  delete "members/leave/:id", to: "members#destroy", as: "leave_group"
  
  post "members/join/:id", to: "members#create", as: "join_group"
  
  get "members/request_to_join/:id", to: "members#request_to_join", as: "request_to_join"
  
  post "posts/share/:id", to: "posts#share", as: "share"
  
  delete "connections/destroy/:id", to: "connections#destroy", as: "unfollow"
  
  post "connections/create/:id", to: "connections#create", as: "follow"
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  post "hashtags/follow/:id", to: "hashtags#follow", as: "follow_tag"
  
  get "posts/new_comment/:id", to: "posts#new_comment", as: "new_comment_ajax"
  
  get "proposals/menu/:proposal_id", to: "proposals#menu", as: "change_proposal_menu"
  
  get "groups/:group_id/proposals/menu", to: "proposals#menu", as: "proposal_menu"
  
  get "federations/:federation_id/proposals/menu", to: "proposals#menu", as: "federation_proposal_menu"
  
  get "groups/:group_id/federations", to: "groups#federations", as: "federations"
  
  delete "users/destroy/:id", to: "users#destroy", as: "user_destroy"
  
  get "users/:user_id/connections", to: "users#connections", as: "user_connections"
  
  get "proposals/new/:proposal_id", to: "proposals#new", as: "new_proposal"
  
  get "proposals/show/:id", to: "proposals#show", as: "proposal"
  
  post "folders/create", as: "create_folder"
  
  post "proposals/create", as: "proposals"
  
  patch "posts/update", as: "update_post"
  
  post "comments/create", as: "comments"
  
  post "messages/create", as: "messages"
  
  get "users/settings", as: "settings"
  
  post "posts/create", as: "posts"
  
  post "shares/create", as: "shares"
  
  get "search/search", as: "search"
  
  get "welcome/about", as: "about"
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  get "sessions/destroy"
  
  get "sessions/new"
  

  
  resources :groups, :federations do
    resources :shares
    resources :members
    resources :code_modules
    resources :proposals do
      resources :comments
    end
  end
  
  resources :users do
    resources :notifications
    member do
      get :following, :followers
    end
    resources :posts do 
      resources :comments
    end
  end
  
  resources :sessions
  resources :connections
  
  resources :folders do
    resources :messages
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :federation
  has_many :posts, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :code_modules, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :hashtags, dependent: :destroy
  has_many :shares, dependent: :destroy
  
  mount_uploader :icon, ImageUploader
  
  def rank
    members.size + (posts.size / 10)
  end
  
  def federations
    _federations = []
    for federation in Federation.all
      for member in federation.members
        if member.federated_group_id == id
          _federations << federation
        end
      end
    end
    return _federations
  end
  
  def membership(user)
    members.find_by_user_id(user)
  end
  
  def self.groups_of(user)
    groups = Array.new
    Member.where("user_id = ?", user.id).each do |member|
      groups << find(member.group) if member.group
    end
    groups
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def groups_joined
    reset_page
    @user = User.find(params[:id])
    @groups = Group.groups_of(@user).
        # drops first several posts if :feed_page
        drop((session[:page] ? session[:page] : 0) * page_size).
        # only shows first several posts of resulting array
        first(page_size)
  end
  
  def federations
    @group = Group.find(params[:group_id])
    @federations = @group.federations
  end
  
  def index
    if current_user
      reset_page
      session[:more] = nil
      # gets groups based on page_size
      @groups = paginate Group.groups_of(current_user).sort_by(&:rank)
    end
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(params[:group].permit(:name, :description, :icon, :private))
    
    if @group.save
      @group.members.create(user_id: current_user.id)
      flash[:notice] = "The group was created successfully."
      redirect_to @group
    else
      flash[:error] = "The group could not be created."
      redirect_to :back
    end
  end
  
  def show
    reset_page
    session[:more] = nil
    # gets group and feed based on page
    @group = Group.find(params[:id])
    @feed = paginate @group.posts.sort_by(&:score)
    @post = Post.new
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_feed.html.erb
<!-- groups feed -->

<% @feed.each do |post| %>
	<%= render "posts/card", post: post %>
<% end %>

app/views/groups/_join.html.erb
<% unless @group.membership(current_user) or !current_user %>
	<% unless @group.private %>
		<%= link_to(join_group_path(@group), class: "btn btn-default", method: :post) do %>
			<span class="glyphicon glyphicon-plus-sign"></span>
		<% end %>
	<% else %>
		<%= link_to(request_to_join_path(@group), class: "btn btn-default") do %>
			<span class="glyphicon glyphicon-plus-sign"></span>
		<% end %>
	<% end %>
<% else %>
	<% if current_user %>
		<%= link_to(leave_group_path(@group), method: :delete, class: "btn btn-default") do %>
			<span class="glyphicon glyphicon-minus-sign"></span>
		<% end %>
	<% end %>
<% end %>

app/views/groups/_name_heading.html.erb
<!-- groups -->

<table align="center">
	<tr>
		<% if @group.icon.url %>
		<td>
			<%= link_to image_tag(@group.icon, size: "50x50", id: :profile_picture), group_path(@group) %>
		</td>
		<% end %>
		<td>
			<% if @group.name.size < 10 %>
				<h2 align="center"><%= @group.name + " " + item %></h2>
			<% else %>
				<h4 align="center"><%= @group.name + " " + item %></h4>
			<% end %>
		</td>
	</tr>
</table></br>

app/views/groups/_profile.html.erb
<!-- groups -->

<div id=<%= color_theme "card" %>>
	<div class="btn-group" id="top_right">
		<%= link_to federations_path(@group), class: "btn btn-default" do %>
			<span class="glyphicon glyphicon-globe"></span>
		<% end %>
		<%= render "join" %>
	</div>
	
	</br>
	<% if @group.name.size < 15 %>
		<h2 align="center"><%= @group.name %></h2>
	<% else %>
		<h4 align="center" id="group_name_heading">
			<%= @group.name %>
		</h4>
	<% end %>
	</br>
	
	<% if @group.icon.url %>
		<div align="center"><%= image_tag @group.icon, width: "60%", id: :profile_picture %></div></br>
	<% end %>
	
	<div align="center"><%= @group.description %></div></br>
	
	<% unless @group.private %>
		<div align="center">
			<div class="btn-group">
				<%= link_to group_members_path(@group), class: "btn btn-default" do %>
					<span class="glyphicon glyphicon-user"></span> Members
				<% end %>
				<%= link_to group_code_modules_path(@group), class: "btn btn-default" do %>
					<span class="glyphicon glyphicon-cog"></span> Modules
				<% end %>
			</div>
			<div class="btn-group">
				<%= link_to group_proposals_path(@group), class: "btn btn-default" do %>
					<span class="glyphicon glyphicon-hand-up"></span> Proposals
				<% end %>
				<%= link_to group_shares_path(@group), class: "btn btn-default" do %>
					<span class="glyphicon glyphicon-tint"></span> Shares
				<% end %>
			</div>
		</div></br>
	<% end %>
</div>

app/views/groups/federations.html.erb
<!-- groups -->

<table align="center">
	<tr>
		<% if @group.icon.url %>
		<td>
			<%= link_to image_tag(@group.icon, size: "50x50", id: :profile_picture), group_path(@group) %>
		</td>
		<% end %>
		<td>
			<h3 align="center"><%= @group.name %> Federations</h3>
		</td>
	</tr>
</table></br>

<% for federation in @federations %>
	<div id="card">
		<table align="center">
			<tr>
				<% if federation.icon.url %>
					<td><%= link_to image_tag(federation.icon, size: "25x25"), federation_path(federation) %></td>
				<% end %>
				<td><%= link_to federation.name, federation_path(federation) %></td>
			</tr>
		</table>
	</div>
<% end %>

<% if @federations.empty? %>
	<div id="card">
		<div align="center">
			<%= link_to @group.name, group_path(@group) %> doesn't belong to any federations yet.
			You can change that by creating a <%= link_to "proposal", proposal_menu_path(@group) %>.
		</div>
	</div>
<% end %>

app/views/groups/groups_joined.html.erb
<!-- groups -->

<% if @groups.empty? %>
	<div id="card">
		<div align="center">
			<%= link_to @user.name.capitalize, user_path(@user) %> hasn't joined any groups.
		</div>
	</div>
<% end %>

<table align="center">
	<tr>
		<% if @user.profile_picture.url %>
		<td>
			<%= profile_picture(@user, "50x50") %>
		</td>
		<% end %>
		<td>
			<% if @user.name.size < 8 %>
				<h2 align="center"><%= @user.name + "'s" %> Groups</h2>
			<% else %>
				<h3 align="center"><%= @user.name + "'s" %> Groups</h3>
			<% end %>
		</td>
	</tr>
</table></br>

<% @groups.reverse.each do |group| %>
	<div id="card">
		<div align="center">
			<% if group.icon.url %>
				<div><%= link_to image_tag(group.icon, size: "50x50",
					id: :profile_picture), group_path(group) %></div>
			<% end %>
			<div><%= link_to group.name, group_path(group) %></div>
		</div>
	</div>
<% end %>

<%= render "pages/more_back", all_items: Group.groups_of(@user), items: @groups %>

app/views/groups/index.html.erb
<% if current_user %>
	<div id="large_button">
		<%= button_to "Start a group", new_group_path, method: :get,
			class: "btn btn-default btn-lg btn-block" %><br>
	</div>

	<% if @groups %>
		<% for group in @groups %>
			<div id=<%= color_theme("card")%>>
				<div align="center">
					<% if group.icon.url %>
						<%= link_to image_tag(group.icon, size: "50x50",
							id: :profile_picture), group_path(group) %>
					<% end %>
					<div><%= link_to group.name, group_path(group) %></div>
				</div>
			</div>
		<% end %>

		<%= render "pages/more_back", all_items: Group.groups_of(current_user), items: @groups %>
	<% end %>
<% else %>
	<div id=<%= color_theme("card")%>>
		<div align="center">
			<%= link_to "Log in", root_url %> or
			<%= link_to "sign up", new_user_path %> to create a group.
		</div>
	</div>
<% end %>

app/views/groups/new.html.erb
<!-- groups -->

<div id="card">
	<div id="form_padding">
		<%= form_for @group, html: {multipart: true, "data-ajax" => false} do |f| %>
			<p>
				<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
			</p>
			<p>
				<%= f.text_area :description, placeholder: "Description", class: "form-control" %>
			</p>
			<p>
				<%= f.file_field :icon, class: "form-control" %>
			</p>
			<p class="form-control">
				<%= f.label :private %>
				<%= f.check_box :private %>
			</p>
			<p>
				<%= f.submit "Create Group", class: "btn btn-default btn-lg btn-block" %>
			</p>
		<% end %>
	</div>
</div>

app/views/groups/show.html.erb
<!-- groups -->

<%= render "profile" %>

<%= render "posts/new", group: @group.id if @group.membership(current_user) %>

<% if @group.membership(current_user) or !@group.private %>
	<%= render "feed" %>
<% end %>

<%= render "pages/more_back", all_items: @group.posts, items: @feed %>

</br>