config/routes.rb
Social::Application.routes.draw do
  root 'welcome#index'
  
  get "users/:user_id/posts/:id/show", to: "posts#show", as: "show_post"
  
  get "comments/show/:id", to: "comments#show", as: "show_comment"
  
  get "comments/down_vote/:id", to: "comments#down_vote", as: "down_vote_comment"
  
  get "comments/up_vote/:id", to: "comments#up_vote", as: "up_vote_comment"
  
  get "posts/down_vote/:id", to: "posts#down_vote", as: "down_vote_post"
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "proposals/up_vote/:id", to: "proposals#up_vote", as: "up_vote_proposal"
  
  get "proposals/down_vote/:id", to: "proposals#down_vote", as: "down_vote_proposal"
  
  get "shares/up_vote/:id", to: "shares#up_vote", as: "up_vote_share"
  
  get "shares/down_vote/:id", to: "shares#down_vote", as: "down_vote_share"
  
  delete "users/:user_id", to: "notifications#clear", as: "clear"
  
  get "groups/groups_joined/:id", to: "groups#groups_joined", as: "groups_joined"
  
  delete "members/leave/:id", to: "members#destroy", as: "leave_group"
  
  post "members/join/:id", to: "members#create", as: "join_group"
  
  get "members/request_to_join/:id", to: "members#request_to_join", as: "request_to_join"
  
  post "posts/share/:id", to: "posts#share", as: "share"
  
  delete "connections/destroy/:id", to: "connections#destroy", as: "unfollow"
  
  post "connections/create/:id", to: "connections#create", as: "follow"
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  post "hashtags/follow/:id", to: "hashtags#follow", as: "follow_tag"
  
  get "posts/new_comment/:id", to: "posts#new_comment", as: "new_comment_ajax"
  
  get "proposals/menu/:proposal_id", to: "proposals#menu", as: "change_proposal_menu"
  
  get "groups/:group_id/proposals/menu", to: "proposals#menu", as: "proposal_menu"
  
  get "federations/:federation_id/proposals/menu", to: "proposals#menu", as: "federation_proposal_menu"
  
  get "groups/:group_id/federations", to: "groups#federations", as: "federations"
  
  delete "users/destroy/:id", to: "users#destroy", as: "user_destroy"
  
  get "users/:user_id/connections", to: "users#connections", as: "user_connections"
  
  get "proposals/new/:proposal_id", to: "proposals#new", as: "new_proposal"
  
  get "proposals/show/:id", to: "proposals#show", as: "proposal"
  
  post "folders/create", as: "create_folder"
  
  post "proposals/create", as: "proposals"
  
  patch "posts/update", as: "update_post"
  
  post "comments/create", as: "comments"
  
  post "messages/create", as: "messages"
  
  get "users/settings", as: "settings"
  
  post "posts/create", as: "posts"
  
  post "shares/create", as: "shares"
  
  get "search/search", as: "search"
  
  get "welcome/about", as: "about"
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  get "sessions/destroy"
  
  get "sessions/new"
  

  
  resources :groups, :federations do
    resources :shares
    resources :members
    resources :code_modules
    resources :proposals do
      resources :comments
    end
  end
  
  resources :users do
    resources :notifications
    member do
      get :following, :followers
    end
    resources :posts do 
      resources :comments
    end
  end
  
  resources :sessions
  resources :connections
  
  resources :folders do
    resources :messages
  end

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :group
  belongs_to :proposal
  belongs_to :federation
  has_many :proposals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  validates :action, presence: true
  
  after_create :creator_up_vote
  
  mount_uploader :icon, ImageUploader
  
  def available_types
    types = [["Proposal type", nil]]
    case self.action.to_sym
      when :icon_change # change proposed icon for group
        types << ["Icon change", "proposal_icon_change"]
      when :name_change # change proposed name for group
        types << ["Name change", "proposal_name_change"]
      when :description_change # proposed description for group
        types << ["Description change", "proposal_description_change"]
      when :add_module # change attributes for proposed module
        types << ["Change code or link", "proposal_module_code_change"]
        types << ["Change module name", "proposal_module_name_change"]
        types << ["Change module description", "proposal_module_description_change"]
      when :req_to_join_federation # propose to request to join a different federation
        types << ["Join different federation", "proposal_req_to_join_dif_federation"]
      when :federate_request
        types << ["Federate with different group", "proposal_federate_w_dif_group"]
        types << ["Change proposed federation name", "proposal_dif_federation_name"]
        types << ["Change proposed federation name", "proposal_dif_federation_description"]
        types << ["Change proposed federation icon", "proposal_dif_federation_icon"]
    end
    return types
  end
  
  def ratify
    group = Group.find_by_id(group_id)
    proposal = Proposal.find_by_id(proposal_id)
    federation = Federation.find_by_id(federation_id)
    federated_federation = Federation.find_by_id(federated_federation_id)
    if (group and ((votes.up_votes.size > group.members.size / 2 and votes.down_votes.empty?) or group.members.size < 2)) or \
      (federation and ((votes.up_votes.size > federation.users.size / 2 and votes.down_votes.empty?) or federation.members.size < 2))
      entity = group ? group : federation
      case action
        when "icon_change"
          entity.update icon: icon
        when "name_change"
          entity.update name: item_name
        when "description_change"
          entity.update description: description
        when "add_module"
          entity.code_modules.create code: submission, icon: icon,
            name: item_name, description: description
        when "request_to_join"
          group.members.create user_id: user_id
        when "req_to_join_federation" # requests to join federation
          federated_federation.proposals.create action: "join_federation", why: why,
            user_id: user_id, federated_group_id: group_id
        when "federate_request" # requests other group to federate
          Group.find(federated_group_id).proposals.create action: "federate", icon: icon,
            item_name: item_name, description: description, federated_group_id: group_id
        when "join_federation" # adds the group to the federation
          federation.members.create federated_group_id: federated_group_id
        when "federate" # other group ratifies and creates the federation
          federation = Federation.create name: item_name, icon: icon, description: description
          federation.members.create federated_group_id: federated_group_id
          federation.members.create federated_group_id: group_id
        when "disband"
          group.destroy
          
        # proposals to proposals
        when "proposal_icon_change", "proposal_dif_federation_icon"
          proposal.update icon: icon
        when "proposal_name_change", "proposal_dif_federation_name", "proposal_module_name_change"
          proposal.update item_name: item_name
        when "proposal_description_change", "proposal_module_description_change", "proposal_dif_federation_description"
          proposal.update description: description
        when "proposal_req_to_join_dif_federation"
          proposal.update federated_federation_id: federated_federation_id
        when "proposal_federate_w_dif_group"
          proposal.update federated_group_id: federated_group_id
        when "proposal_module_code_change"
          proposal.update submission: submission
      end
      # ends voting of proposal after ratification
      update ratified: true
    end
  end
  
  def score
    Vote.score(self)
  end
  
  private
  
  def creator_up_vote
    if user_id or anonymous
      votes.create up: true, voter: user_id
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def menu
    if params[:group_id]
      @group = Group.find(params[:group_id])
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
    elsif params[:proposal_id]
      @proposal = Proposal.find(params[:proposal_id])
    end
  end
  
  def new
    session[:proposal_type] = params[:proposal_type] if params[:proposal_type].present?
    @_proposal = Proposal.find_by_id(params[:proposal_id]) # the old proposal being changed
    @federations = Federation.all
    @proposal = Proposal.new
    
    if params[:group_id]
      @groups = Group.where.not(id: params[:group_id])
    else
      @groups = Group.all
    end
  end
  
  def up_vote
    @proposal = Proposal.find(params[:id])
    Vote.up_vote!(@proposal, current_user)
    # ratifies proposal at enough votes
    if @proposal.ratify
      flash[:notice] = "The proposal has been ratified!"
      if Proposal.where(id: @proposal.id).present?
        redirect_to :back
      else
        redirect_to groups_path
      end
    else
      redirect_to :back
    end
  end
  
  def down_vote
    @proposal = Proposal.find(params[:id])
    Vote.down_vote!(@proposal, current_user)
    redirect_to :back
  end
  
  def show
    if params[:group_id]
      @group = Group.find(params[:group_id])
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
    end
    @proposal = Proposal.find(params[:id])
    @comment = Comment.new
  end
  
  def index
    if params[:group_id]
      @group = Group.find(params[:group_id])
      @proposals = @group.proposals.sort_by(&:score).reverse!
      
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
      @proposals = @federation.proposals.sort_by(&:score).reverse!
    end
  end
  
  def create
    if params[:group_id]
      @group = Group.find(params[:group_id])
      _obj = @group
    elsif params[:federation_id]
      @federation = Federation.find(params[:federation_id])
      _obj = @federation
    elsif params[:proposal_id]
      @proposal = Proposal.find(params[:proposal_id])
      _obj = @proposal
    end
    @new_proposal = _obj.proposals.new(params[:proposal].permit(:submission, :federated_federation_id,
      :description, :icon, :anonymous, :item_name, :federated_group_id, :why))
    @new_proposal.user_id = params[:user_id] unless params[:anonymous] == 1
    @new_proposal.action = session[:proposal_type]
    if @new_proposal.save
      @new_proposal.ratify if @group and @group.members.size < 2
      if @group
        if Group.find_by_id(@group.id)
          redirect_to group_proposals_path(@group)
        else
          redirect_to groups_path
        end
      elsif @federation
        if Federation.find_by_id(@federation.id)
          redirect_to federation_proposals_path(@federation)
        else
          redirect_to root_url
        end
      elsif @proposal
        if @proposal.group_id
          redirect_to group_proposal_path(Group.find(@proposal.group_id), @proposal)
        elsif @proposal.federation_id
          redirect_to federation_proposal_path(Federation.find(@proposal.federation_id), @proposal)
        end
      end
    else
      flash[:error] = "Invalid input"
      redirect_to :back
    end
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_card.html.erb
<!-- proposals -->

<div id="card">
	<%= render "proposals/time_ago", proposal: proposal %>
	<% if @group or proposal.proposal_id %>
		<%= render "user_action", proposal: proposal %>
	<% elsif @federation %>
		<%= render "federated_user_action", proposal: proposal %>
	<% end %>
	
	<%= render "content", proposal: proposal %>

	<div id="post_buttons">
		<div class="btn-group">
			<%= render "proposals/vote", proposal: proposal %>
			<%= render "proposals/comment", proposal: proposal %>
		</div>
	</div>
</div>

app/views/proposals/_comment.html.erb
<!-- proposals comment button -->

<% if @group %>
	<%= link_to(group_proposal_path(@group, proposal), class: "btn btn-default") do %>
		<span class="glyphicon glyphicon-comment"></span>
	<% end %>
<% elsif @federation %>
	<%= link_to(federation_proposal_path(@federation, proposal), class: "btn btn-default") do %>
		<span class="glyphicon glyphicon-comment"></span>
	<% end %>
<% else %>
	<%= link_to(proposal_path(proposal), class: "btn btn-default") do %>
		<span class="glyphicon glyphicon-comment"></span>
	<% end %>
<% end %>

app/views/proposals/_content.html.erb
<div align="center" id="proposals_content">
	<% if proposal.action == "add_module" %>
		<strong><p><%= proposal.item_name %></p></strong>
	<% end %>
	
	<% if proposal.icon? %>
		<div>
			<%= image_tag(proposal.icon, width: "50%") %>
		</div></br>
	<% end %>
	
	<% if proposal.action == "add_module" %>
		<% if proposal.submission =~ /\A#{URI::regexp}\z/ %>
			<%= link_to proposal.submission, proposal.submission %>
		<% else %>
			<pre align="left"><%= beautify proposal.submission %></pre>
		<% end %>
	<% end %>

	<% unless proposal.why.nil? or proposal.why.empty? %>
		<div><strong>Why:</strong> <%= proposal.why %></div>
	<% end %>
</div>

app/views/proposals/_federated_user_action.html.erb
<% name = @federation.name %>
<% group = Group.find(proposal.federated_group_id) if proposal.federated_group_id %>
<% user = User.find_by_id(proposal.user_id) %>

<p align="center">
	<% if proposal.anonymous %>
		Anonymous
	<% elsif proposal.action == "federate" %>
		<%= link_to group.name, group_path(group) %>
	<% else %>
		<%= link_to User.find(proposal.user_id).name, user_path(proposal.user_id) if proposal.user_id %>
	<% end %>

	<% case proposal.action %>
		<% when "name_change" %>
			proposes that <%= link_to name, federation_path(@federation) %>
			should change its name to "<%= proposal.submission.capitalize %>"
		<% when "description_change" %>
			proposed that <%= link_to name, federationfederation_path(@federation) %>
			should change its description to "<%= proposal.submission %>"
		<% when "add_module" %>
			proposed to add a software module to <%= link_to name, federation_path(@federation) %>
		<% when "icon_change" %>
			proposed that <%= link_to name, federation_path(@federation) %> should change its icon
		<% when "join_federation" %>
			proposed that <%= link_to group.name, group_path(group) %> should join
			<%= link_to @federation.name, federation_path(@federation) %>
		<% when "request_to_join" %>
			requested to join <%= link_to name, federation_path(@federation) %>
		<% when "disband" %>
			proposed that <%= link_to name, federation_path(@federation) %> should disband
	<% end %>
</p>

app/views/proposals/_federation_proposals.html.erb
<!-- proposals -->

<%= render "federations/name_heading", item: "Proposals" %>

<% if current_user and @proposals.present? %>
<div id="large_button">
	<%= button_to "Create a proposal", federation_proposal_menu_path(@federation),
		method: :get, class: "btn btn-default btn-lg btn-block" %><br>
</div>
<% end %>

<% @proposals.each do |proposal| %>
	<div id="card">
		<%= render "federated_user_action", proposal: proposal %>
		
		<%= render "content", proposal: proposal %>
		
		<div align="center">
			<div class="btn-group">
				<%= render "proposals/vote", proposal: proposal %>
				<%= render "proposals/comment", proposal: proposal %>
			</div>
		</div>
	</div>
<% end %>

<% if @proposals.empty? %>
	<div id="card">
		<div align="center">
			<%= link_to @federation.name, federation_path(@federation) %> doesn't have any proposals yet.
			To create one, click <%= link_to "here", federation_proposal_menu_path(@federation) %>.
		</div>
	</div>
<% end %>

app/views/proposals/_group_proposals.html.erb
<!-- proposals -->

<%= render "groups/name_heading", item: "Proposals" %>

<% if current_user and @proposals.present? and @group.membership(current_user) %>
<div id="large_button">
	<%= link_to "Change the group", proposal_menu_path(@group), class: "btn btn-default btn-lg btn-block" %>
</div>
<% end %>

<% @proposals.each do |proposal| %>
	<% if proposal.federated_group_id.nil? or Group.find_by_id(proposal.federated_group_id) %>
		<%= render "proposals/card", proposal: proposal %>
	<% end %>
<% end %>

<% if @proposals.empty? %>
	<div id="card">
		<div align="center">
			<%= link_to @group.name, group_path(@group) %> doesn't have any proposals yet.
			To create one, click <%= link_to "here", proposal_menu_path(@group) %>.
		</div>
	</div>
<% end %>

</br>

app/views/proposals/_time_ago.html.erb
<!-- proposals -->

<!-- time variables gets set -->
<% time_ago = time_ago_in_words(proposal.created_at) + " ago" %>
<% if time_ago.include? "about" %>
	<% time_ago.slice! "about " %>
<% end %>

<%= link_to time_ago, proposal_path(proposal), id: :top_left_link %>

app/views/proposals/_user_action.html.erb
<% name = @group.name if @group %>
<% other_group = Group.find(proposal.federated_group_id) if proposal.federated_group_id %>

<div align="center" id="proposal_action_text">
	<% if proposal.anonymous %>
		Anonymous
	<% elsif other_group and proposal.action == "federate" %>
		<%= link_to other_group.name, group_path(other_group) %>
	<% else %>
		<%= link_to User.find(proposal.user_id).name, user_path(proposal.user_id) if proposal.user_id %>
	<% end %>

	<% case proposal.action %>
		<% when "name_change" %>
			proposed that <%= link_to name, group_path(@group) %>
			should change its name to "<%= proposal.item_name %>"
		<% when "description_change" %>
			proposed that <%= link_to name, group_path(@group) %>
			should change its description to "<%= proposal.description %>"
		<% when "add_module" %>
			proposed to add a module to <%= link_to name, group_path(@group) %>
		<% when "icon_change" %>
			proposed that <%= link_to name, group_path(@group) %> should change its icon
		<% when "private_group" %>
			proposed that <%= link_to name, group_path(@group) %> should be private
		<% when "public_group" %>
			proposed that <%= link_to name, group_path(@group) %> should be public
		<% when "request_to_join" %>
			requested to join <%= link_to name, group_path(@group) %>
		<% when "federate_request" %>
			proposed a federation between <%= link_to name, group_path(@group) %>
			and <%= link_to other_group.name, group_path(other_group) %>
		<% when "req_to_join_federation", "join_federation" %>
			proposed that <%= link_to name, group_path(@group) %> should join 
			<%= link_to Federation.find(proposal.federated_federation_id).name,
				federation_path(proposal.federated_federation_id) %>
		<% when "federate" %>
			proposed a federation with <%= link_to name, group_path(@group) %>
		<% when "disband" %>
			proposed that <%= link_to name, group_path(@group) %> should disband
		
		
		<!-- proposals to change proposals -->
		
		<% when "proposal_name_change" %>
			proposed that the name be changed to "<%= proposal.item_name %>" instead
		<% when "proposal_icon_change" %>
			proposed a different icon
		<% when "proposal_description_change" %>
			proposed a different description
		<% when "proposal_module_code_change" %>
			proposed a different source for the module
		<% when "proposal_module_name_change" %>
			proposed different name for the module: "<%= proposal.item_name %>"
		<% when "proposal_module_description_change" %>
			proposed a different description for the module
		<% when "proposal_req_to_join_dif_federation" %>
			proposed the group request to join a different federation
		<% when "proposal_federate_w_dif_group" %>
			proposed the group federate with a different group
		<% when "proposal_dif_federation_name" %>
			proposed different name for the federation: "<%= proposal.item_name %>"
		<% when "proposal_dif_federation_description" %>
			proposed a different description for the federation
		<% when "proposal_dif_federation_icon" %>
			proposed a different icon for the federation
	<% end %>
</div>

app/views/proposals/_vote.html.erb
<!-- proposals vote -->

<% if (proposal.proposal_id or (@federation and @federation.membership(current_user)) or \
	(@group and @group.membership(current_user))) and current_user.id != proposal.user_id %>
	<% unless proposal.ratified %>
		<%= link_to(up_vote_proposal_path(proposal), class: "btn btn-default") do %>
			<span class="glyphicon glyphicon-chevron-up"></span>
		<% end %>
		<%= link_to(down_vote_proposal_path(proposal), class: "btn btn-default") do %>
			<span class="glyphicon glyphicon-chevron-down"></span>
		<% end %>
	<% end %>
<% end %>

app/views/proposals/down_vote.js.erb
alert("The post was successfully down voted.");

app/views/proposals/menu.html.erb
<div id="card">
	<div id="form_padding">
	<% if current_user %>
		<% if @group and @group.membership(current_user) %>
			<%= form_tag new_group_proposal_path(@group), method: :get do %>
				<%= hidden_field_tag :group_id, params[:group_id] %>
				<p>Choose a proposal type</p>
				<p>
					<%= select_tag :proposal_type,
						options_for_select([["Proposal type", nil], ["Federate", "federate_request"],
						["Join federation", "req_to_join_federation"], ["Description change", "description_change"],
						["Add a module", "add_module"], ["Name change", "name_change"], ["Icon change", "icon_change"],
						["Disband", "disband"]]), class: "form-control" %>
				</p>
				<p>
					<%= submit_tag "Next", class: "btn btn-default btn-lg btn-block" %>
				</p>
			<% end %>
		<% elsif @group %>
			<div align="center">
				Join this <%= link_to "group", group_path(@group) %> to create a proposal.
			</div>
		<% end %>
		
		<% if @federation and @federation.membership(current_user) %>
			<%= form_tag new_federation_proposal_path(@federation), method: :get do %>
				<%= hidden_field_tag :federation_id, params[:federation_id] %>
				<p>Choose a proposal type</p>
				<p>
					<%= select_tag :proposal_type,
						options_for_select([["Proposal type", nil], ["Request group to join", "request_group_to_join"],
						["Description change", "description_change"], ["Add a module", "add_module"],
						["Name change", "name_change"], ["Icon change", "icon_change"],
						["Disband", "disband"]]), class: "form-control" %>
				</p>
				<p>
					<%= submit_tag "Next", class: "btn btn-default btn-lg btn-block" %>
				</p>
			<% end %>
		<% elsif @federation %>
			<div align="center">
				Join a <%= link_to "group", federation_members_path(@federation) %>
				of the <%= link_to "federation", federation_path(@federation) %>
				to create a proposal.
			</div>
		<% end %>
		
		<% if @proposal %>
			<%= form_tag new_proposal_path(@proposal), method: :get do %>
				<%= hidden_field_tag :proposal_id, params[:proposal_id] %>
				<p>Choose a proposal type</p>
				<p>
					<%= select_tag :proposal_type, options_for_select(@proposal.available_types), class: "form-control" %>
				</p>
				<p>
					<%= submit_tag "Next", class: "btn btn-default btn-lg btn-block" %>
				</p>
			<% end %>
		<% end %>
		
	<% else %>
		<div align="center">
			<%= link_to "Log in", root_url %> or
			<%= link_to "sign up", new_user_path %> to create a proposal.
		</div>
	<% end %>
	</div>
</div>

app/views/proposals/new.html.erb
<!-- proposals -->

<div id="card">
	<% if current_user and session[:proposal_type] %>
	<div id="form_padding">
	<%= form_for @proposal, :html => {:multipart => true, "data-ajax" => false} do |f| %>
		<%= hidden_field_tag(:federation_id, params[:federation_id]) if params[:federation_id] %>
		<%= hidden_field_tag(:proposal_id, params[:proposal_id]) if params[:proposal_id] %>
		<%= hidden_field_tag(:group_id, params[:group_id]) if params[:group_id] %>
		<%= hidden_field_tag :user_id, current_user.id %>
	
		<% case session[:proposal_type] %>
			<% when "description_change" %>
				<p>
					<%= f.text_area :description, placeholder: "New description", class: "form-control" %>
				</p>
			<% when "add_module" %>
				<p>
					<%= f.label "Choose an icon for the module" %>
					<%= f.file_field :icon, class: "form-control" %>
				</p>
				<p>
					<%= f.text_field :item_name, placeholder: "Module name", class: "form-control" %>
				</p>
				<p>
					<%= f.text_area :submission, placeholder: "Provide the link or HTML", class: "form-control" %>
				</p>
				<p>
					<%= f.text_area :description, placeholder: "Describe the module", class: "form-control" %>
				</p>
			<% when "federate_request" %>
				<p align="center">Create a federation of groups</p>
				<p>
					<%= f.text_field :item_name, placeholder: "Name", class: "form-control" %>
				</p>
				<p>
					The group you want to federate with
					<%= f.select :federated_group_id, options_from_collection_for_select(@groups,
						:id, :name), {}, class: "form-control" %>
				</p>
				<p>
					Upload an icon for the federation
					<%= f.file_field :icon, class: "form-control" %>
				</p>
				<p>
					<%= f.text_field :description, placeholder: "Description", class: "form-control" %>
				</p>
			<% when "req_to_join_federation" %>
				<p>
					The federation you want to join
					<%= f.select :federated_federation_id, options_from_collection_for_select(@federations,
						:id, :name), {}, class: "form-control" %>
				</p>
			<% when "name_change" %>
				<p>
					<%= f.text_area :item_name, placeholder: "New name", class: "form-control" %>
				</p>
			<% when "icon_change" %>
				<p>
					<%= f.label "Choose a new icon image" %>
					<%= f.file_field :icon, class: "form-control" %>
				</p>
			
			
			<!-- fields for proposals to proposals -->
			<% when "proposal_icon_change" %>
				<p>
					<%= f.label "Propose a different icon for the group" %>
					<%= f.file_field :icon, class: "form-control" %>
				</p>
			<% when "proposal_name_change" %>
				Proposed name change for the group: <%= @_proposal.item_name %>
				<p>
					<%= f.text_field :item_name, placeholder: "Propose a different name for the group", class: "form-control" %>
				</p>
			<% when "proposal_description_change" %>
				<p>
					<%= f.text_area :description, placeholder: "Propose a different description for the group", class: "form-control" %>
				</p>
			<% when "proposal_module_code_change" %>
				<p>
					<%= f.text_area :submission, placeholder: "Propose a different source for the module", class: "form-control" %>
				</p>
			<% when "proposal_module_name_change" %>
				Proposed name for the module: <%= @_proposal.item_name %>
				<p>
					<%= f.text_field :item_name, placeholder: "Propose a different name for the module", class: "form-control" %>
				</p>
			<% when "proposal_module_description_change" %>
				<p>
					<%= f.text_area :description, placeholder: "Propose a different description for the module", class: "form-control" %>
				</p>
			<% when "proposal_req_to_join_dif_federation" %>
				<p>
					Propose to join a different federation
					<%= f.select :federated_federation_id, options_from_collection_for_select(@federations,
						:id, :name), {}, class: "form-control" %>
				</p>
			<% when "proposal_federate_w_dif_group" %>
				<p>
					Propose to join a different group
					<%= f.select :federated_group_id, options_from_collection_for_select(@groups,
						:id, :name), {}, class: "form-control" %>
				</p>
			<% when "proposal_dif_federation_name" %>
				Proposed name for the federation: <%= @_proposal.item_name %>
				<p>
					<%= f.text_field :item_name, placeholder: "Propose a different name for the federation", class: "form-control" %>
				</p>
			<% when "proposal_dif_federation_description" %>
				<p>
					<%= f.text_field :description, placeholder: "Propose a different description for the federation", class: "form-control" %>
				</p>
			<% when "proposal_dif_federation_icon" %>
				<p>
					Upload a different icon for the proposed federation
					<%= f.file_field :icon, class: "form-control" %>
				</p>
		<% end %>
	
		<p>
			<%= f.text_area :why, placeholder: "Why (optional)", class: "form-control" %>
		</p>

		<p class="form-control">
			<%= f.label :anonymous %>
			<%= f.check_box :anonymous %>
		</p>
	
		<p>
			<%= f.submit "Create proposal", class: "btn btn-default btn-lg btn-block" %>
		</p>
	<% end %>
	</div>
<% else %>
	<div align="center">Try logging in or choosing a proposal type.</div>
<% end %>
</div>

app/views/proposals/show.html.erb
<!-- proposals -->

<% if current_user and not @proposal.ratified %>
<div id="large_button">
	<%= link_to "Change the proposal", change_proposal_menu_path(@proposal), class: "btn btn-default btn-lg btn-block" %>
</div>
<% end %>

<%= render "proposals/card", proposal: @proposal %>

<% for proposal in @proposal.proposals %>
	<%= render "proposals/card", proposal: proposal %>
<% end %>

<%= render "proposals/comments" %>

<%= render "comments/new", item: :proposal %>

</br>

app/views/proposals/up_vote.js.erb
alert("The post was successfully up voted.");